"""Add competition field to matches

Revision ID: e1615176bf58
Revises: c163250aeda1
Create Date: 2026-01-24 20:39:40.403294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1615176bf58'
down_revision: Union[str, None] = 'c163250aeda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All existing matches are Premier League
    op.add_column('matches', sa.Column('competition', sa.String(length=10), nullable=False, server_default='PL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'competition')
    # ### end Alembic commands ###
