"""Add referees managers and enhanced stats

Revision ID: c163250aeda1
Revises: 001
Create Date: 2026-01-24 20:18:50.238031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c163250aeda1'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('matches_officiated', sa.Integer(), nullable=False),
    sa.Column('avg_fouls_per_game', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('avg_yellow_cards', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('avg_red_cards', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('penalties_awarded', sa.Integer(), nullable=False),
    sa.Column('home_win_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('manager_tenures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_interim', sa.Boolean(), nullable=False),
    sa.Column('matches_managed', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manager_tenures_team_current', 'manager_tenures', ['team_id', 'end_date'], unique=False)
    op.alter_column('elo_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('match_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('match_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('matches', sa.Column('referee_id', sa.Integer(), nullable=True))
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'matches', 'referees', ['referee_id'], ['id'])
    op.alter_column('odds_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('team_stats', sa.Column('injury_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('team_stats', sa.Column('key_players_out', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('team_stats', sa.Column('manager_games', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('team_stats', sa.Column('is_new_manager', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('team_stats', sa.Column('transfer_impact', sa.Integer(), nullable=True))
    op.alter_column('team_stats', 'goals_scored',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'goals_conceded',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'home_wins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'home_draws',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'home_losses',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'away_wins',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'away_draws',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'away_losses',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'clean_sheets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'failed_to_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('team_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('team_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('value_bets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('value_bets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('value_bets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('value_bets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('value_bets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('value_bets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_stats', 'failed_to_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'clean_sheets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'away_losses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'away_draws',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'away_wins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'home_losses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'home_draws',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'home_wins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'goals_conceded',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team_stats', 'goals_scored',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('team_stats', 'transfer_impact')
    op.drop_column('team_stats', 'is_new_manager')
    op.drop_column('team_stats', 'manager_games')
    op.drop_column('team_stats', 'key_players_out')
    op.drop_column('team_stats', 'injury_count')
    op.alter_column('odds_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('matches', 'referee_id')
    op.alter_column('match_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('match_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('elo_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_manager_tenures_team_current', table_name='manager_tenures')
    op.drop_table('manager_tenures')
    op.drop_table('referees')
    op.drop_table('managers')
    # ### end Alembic commands ###
