"""Add team fixtures table

Revision ID: 77fd65dee607
Revises: e1615176bf58
Create Date: 2026-01-24 20:43:03.661338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fd65dee607'
down_revision: Union[str, None] = 'e1615176bf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('competition', sa.String(length=10), nullable=False),
    sa.Column('opponent_name', sa.String(length=100), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'kickoff_time', 'competition', name='uq_team_fixture')
    )
    op.create_index('ix_team_fixtures_team_kickoff', 'team_fixtures', ['team_id', 'kickoff_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_fixtures_team_kickoff', table_name='team_fixtures')
    op.drop_table('team_fixtures')
    # ### end Alembic commands ###
